In [89]:
import pandas as pd
import numpy as np

In [90]:
date = pd.read_csv('orders.csv')
date.sample(5)

           date  product_id  city_id  orders
945  2018-07-17        2568       22       8
128  2019-11-23        6204       24       2
394  2018-12-16        7034       13       1
195  2019-05-01        5470       16      23
315  2018-11-10        3345       13      23

In [124]:
time = pd.read_csv('messages.csv')
time.sample(5)

                    date                                                msg
121  2013-12-09 01:09:00              холостяк хочет познакомится 40л богат
823  2013-10-29 00:36:00  Ж.38(инвалид 2группы) в Днепре есть М.38-45???...
527  2014-05-27 00:25:00  мне 33 ищу   девушку для новых отношений..днеп...
31   2013-03-03 00:58:00  . Мне 36. Хочу женщину 50-55лет. Жду смс ммс. ...
110  2012-12-12 01:23:00                  ХОЛОСТЯК ИЩЕТ ДЕВУШКУ. 0935322713

# Working with Date Column:

In [92]:
date.sample(5)

           date  product_id  city_id  orders
246  2019-12-10        2253       13      46
609  2018-10-21        1933       21      19
646  2018-09-01        7399        0      39
499  2018-09-28        1225       13      40
207  2019-04-01        5135        9       5

In [93]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [94]:
date['date'] = pd.to_datetime(date['date'])

In [95]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

### 1: Extract Year:

In [96]:
date['date_year'] = date['date'].dt.year
date.sample(5)

          date  product_id  city_id  orders  date_year
669 2018-10-31        1647        4       1       2018
659 2019-06-01        3140       26       2       2019
251 2018-11-14        7239       22       1       2018
897 2018-10-09        2502       13       5       2018
353 2018-08-08        2284        9       8       2018

### 2: Extract Month:

In [97]:
date['date_month'] = date['date'].dt.month
date.sample(5)

          date  product_id  city_id  orders  date_year  date_month
769 2019-08-09         408        9       2       2019           8
867 2019-12-16         335       13       3       2019          12
747 2018-08-06        2490        7       9       2018           8
557 2019-01-22        2811       13       9       2019           1
362 2019-10-10        3734        4      25       2019          10

In [98]:
date['date_month_name'] = date['date'].dt.month_name()
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name
475,2019-07-25,2898,18,98,2019,7,July
785,2019-11-28,7427,28,1,2019,11,November
792,2019-03-31,5843,9,1,2019,3,March
730,2019-06-22,2607,22,1,2019,6,June
856,2019-10-18,4594,22,6,2019,10,October

### 3: Extract Day:

In [99]:
date['date_day'] = date['date'].dt.day
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day
511,2018-12-02,1403,29,3,2018,12,December,2
607,2019-05-27,3685,0,1,2019,5,May,27
185,2019-11-29,4294,14,4,2019,11,November,29
371,2019-12-02,820,30,8,2019,12,December,2
569,2019-02-18,5795,14,4,2019,2,February,18

In [100]:
date['date_day_of_week'] = date['date'].dt.dayofweek
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_of_week
902,2019-03-24,5031,0,6,2019,3,March,24,6
747,2018-08-06,2490,7,9,2018,8,August,6,0
463,2018-11-21,1945,9,3,2018,11,November,21,2
726,2019-10-20,5794,6,1,2019,10,October,20,6
291,2018-11-20,5009,28,12,2018,11,November,20,1

In [101]:
date['date_day_name'] = date['date'].dt.day_name()
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_of_week,date_day_name
178,2019-04-30,4776,16,100,2019,4,April,30,1,Tuesday
798,2018-07-23,154,26,4,2018,7,July,23,0,Monday
379,2019-10-11,2381,18,23,2019,10,October,11,4,Friday
603,2018-12-11,7435,22,2,2018,12,December,11,1,Tuesday
97,2018-09-27,4690,23,1,2018,9,September,27,3,Thursday

In [102]:
date['is_weekend'] = np.where(date['date_day_of_week'].isin([5, 6]), 1, 0)
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_of_week,date_day_name,is_weekend
109,2018-08-08,351,20,1,2018,8,August,8,2,Wednesday,0
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1
153,2019-01-13,4576,22,1,2019,1,January,13,6,Sunday,1
994,2018-10-23,785,16,1,2018,10,October,23,1,Tuesday,0
548,2019-11-03,5917,2,59,2019,11,November,3,6,Sunday,1

In [103]:
date['date_week_of_year'] = date['date'].dt.isocalendar().week
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_of_week,date_day_name,is_weekend,date_week_of_year
937,2019-08-19,1047,30,5,2019,8,August,19,0,Monday,0,34
137,2019-03-14,2087,26,1,2019,3,March,14,3,Thursday,0,11
575,2018-09-27,4627,26,1,2018,9,September,27,3,Thursday,0,39
845,2019-02-27,5363,23,1,2019,2,February,27,2,Wednesday,0,9
688,2019-04-06,2154,26,4,2019,4,April,6,5,Saturday,1,14

In [104]:
date['date_quarter_of_year'] = date['date'].dt.quarter
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_of_week,date_day_name,is_weekend,date_week_of_year,date_quarter_of_year
640,2018-11-03,3161,21,1,2018,11,November,3,5,Saturday,1,44,4
38,2019-02-15,7025,14,33,2019,2,February,15,4,Friday,0,7,1
533,2019-01-22,6291,27,1,2019,1,January,22,1,Tuesday,0,4,1
440,2018-10-31,4382,23,5,2018,10,October,31,2,Wednesday,0,44,4
672,2019-09-18,779,16,1,2019,9,September,18,2,Wednesday,0,38,3

In [105]:
date['date_semester'] = np.where(date['date_quarter_of_year'].isin([1, 2]), 1, 2)
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_of_week,date_day_name,is_weekend,date_week_of_year,date_quarter_of_year,date_semester
128,2019-11-23,6204,24,2,2019,11,November,23,5,Saturday,1,47,4,2
388,2019-01-19,4075,18,25,2019,1,January,19,5,Saturday,1,3,1,1
810,2019-06-25,1187,2,45,2019,6,June,25,1,Tuesday,0,26,2,1
578,2019-06-28,5922,25,2,2019,6,June,28,4,Friday,0,26,2,1
315,2018-11-10,3345,13,23,2018,11,November,10,5,Saturday,1,45,4,2

### Elapsed between Dates:

In [106]:
import datetime

today = datetime.datetime.today()
today

datetime.datetime(2026, 8, 12, 12, 32, 27, 751420)

In [107]:
today - date['date']

0     2437 days 12:32:27.751420
1     2919 days 12:32:27.751420
2     2850 days 12:32:27.751420
3     2552 days 12:32:27.751420
4     2775 days 12:32:27.751420
                 ...
995   2865 days 12:32:27.751420
996   2806 days 12:32:27.751420
997   2654 days 12:32:27.751420
998   2719 days 12:32:27.751420
999   2493 days 12:32:27.751420
Name: date, Length: 1000, dtype: timedelta64[ns]

In [108]:
(today - date['date']).dt.days

0      2437
1      2919
2      2850
3      2552
4      2775
       ...
995    2865
996    2806
997    2654
998    2719
999    2493
Name: date, Length: 1000, dtype: int64

In [109]:
(np.round((today - date['date']) / np.timedelta64(1, 'W'),0)) / 7

0      49.714286
1      59.571429
2      58.142857
3      52.142857
4      56.714286
         ...
995    58.428571
996    57.285714
997    54.142857
998    55.571429
999    50.857143
Name: date, Length: 1000, dtype: float64

# Working with Time:

In [125]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [126]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [127]:
time['date'] = pd.to_datetime(time['date'])
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [128]:
time['dates'] = time['date'].dt.date
time['time'] = time['date'].dt.time

time.head()

,date,msg,dates,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,2013-12-15,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,2014-04-29,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,2012-12-30,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,2014-11-28,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,2013-10-26,23:11:00

In [129]:
time['hour'] = time['date'].dt.hour
time['minute'] = time['date'].dt.minute
time['second'] = time['date'].dt.second

time.head()

,date,msg,dates,time,hour,minute,second
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,2013-12-15,00:50:00,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,2014-04-29,23:40:00,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,2012-12-30,00:21:00,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,2014-11-28,00:31:00,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,2013-10-26,23:11:00,23,11,0

In [130]:
today - time['date']

0     4623 days 11:42:27.751420
1     4487 days 12:52:27.751420
2     4973 days 12:11:27.751420
3     4275 days 12:01:27.751420
4     4672 days 13:21:27.751420
                 ...
995   5262 days 11:42:27.751420
996   4583 days 13:18:27.751420
997   5048 days 12:55:27.751420
998   5164 days 12:58:27.751420
999   4436 days 13:07:27.751420
Name: date, Length: 1000, dtype: timedelta64[ns]

In [131]:
(today - time['date']) / np.timedelta64(1, 'W')

0      660.498260
1      641.076633
2      710.501137
3      610.785859
4      667.508082
          ...
995    751.783974
996    654.793498
997    721.219788
998    737.791514
999    633.792407
Name: date, Length: 1000, dtype: float64

In [132]:
(today - time['date']) / np.timedelta64(1, 's')

0      3.994693e+08
1      3.877231e+08
2      4.297111e+08
3      3.694033e+08
4      4.037089e+08
           ...
995    4.546789e+08
996    3.960191e+08
997    4.361937e+08
998    4.462163e+08
999    3.833176e+08
Name: date, Length: 1000, dtype: float64