In [1]:
import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score, precision_score, recall_score, classification_report

## Binary Classification Metrics:

In [2]:
df = pd.read_csv('D:/Important Files/Machine Learning/Datasets/heart.csv')
df.head(5)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [3]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 0:13], df.iloc[:, -1], test_size=0.2, random_state=2)

In [4]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [5]:
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

### Accuracy Score:

In [6]:
print("Accuracy of Logistic Regression:", accuracy_score(y_test, y_pred))

Accuracy of Logistic Regression: 0.8852459016393442

### Confusion Matrix:

In [7]:
confusion_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", confusion_mat)

Confusion Matrix:
 [[26  6]
 [ 1 28]]

### Recall (Sensitivity):

In [8]:
recall = recall_score(y_test, y_pred)
print("Recall:", recall)

Recall: 0.9655172413793104

### Precision:

In [9]:
precision = precision_score(y_test, y_pred)
print("Precision:", precision)

Precision: 0.8235294117647058

### F1-Score:

In [10]:
f1 = f1_score(y_test, y_pred)
print("F1 Score:", f1)

F1 Score: 0.8888888888888888

### Classification Report:

In [11]:
print("Classification Report:\n", classification_report(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.81      0.88        32
           1       0.82      0.97      0.89        29

    accuracy                           0.89        61
   macro avg       0.89      0.89      0.89        61
weighted avg       0.90      0.89      0.88        61

---

## Multiclass Classification Metrics:

In [12]:
df1 = pd.read_csv('D:/Important Files/Machine Learning/Datasets/MNIST.csv')
df1.head(5)

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(df1.iloc[:, 1:], df1.iloc[:, 0], test_size=0.2, random_state=2)

In [14]:
X_train1 = X_train1 / 255.0
X_test1 = X_test1 / 255.0

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train1, y_train1)
y_pred1 = lr.predict(X_test1)

### Accuracy Score:

In [15]:
print("Accuracy of Logistic Regression:", accuracy_score(y_test1, y_pred1))

Accuracy of Logistic Regression: 0.9185714285714286

### Confusion Matrix:

In [16]:
confusion_mat1 = confusion_matrix(y_test1, y_pred1)
print("Confusion Matrix:\n", confusion_mat1)

Confusion Matrix:
 [[792   0   1   0   1  11  10   1   4   1]
 [  0 939   1   5   0   4   0   3  10   0]
 [  3  10 747  13  11   3  10  12  16   4]
 [  0   6  19 765   0  32   3   8  20  11]
 [  1   4   4   0 807   2   8   2   4  24]
 [  5   2   3  23  11 634   9   8  24  10]
 [ 14   3  12   2   5   8 790   0   5   0]
 [  1   2  18   5   4   1   0 814   1  27]
 [ 12  12  11  19   0  20   7   6 690  16]
 [  5   6   2  12  22   6   0  36   7 738]]

### Recall (Sensitivity):

In [17]:
recall = recall_score(y_test1, y_pred1, average='macro')
print("Recall:", recall)

Recall: 0.9168732191555307

### Precision:

In [18]:
precision = precision_score(y_test1, y_pred1, average='macro')
print("Precision:", precision)

Precision: 0.9171289302518973

### F1-Score:

In [19]:
f1 = f1_score(y_test1, y_pred1, average='macro')
print("F1 Score:", f1)

F1 Score: 0.9169498026713292

### Classification Report:

In [20]:
print("Classification Report:\n", classification_report(y_test1, y_pred1))

Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.96      0.96       821
           1       0.95      0.98      0.97       962
           2       0.91      0.90      0.91       829
           3       0.91      0.89      0.90       864
           4       0.94      0.94      0.94       856
           5       0.88      0.87      0.87       729
           6       0.94      0.94      0.94       839
           7       0.91      0.93      0.92       873
           8       0.88      0.87      0.88       793
           9       0.89      0.88      0.89       834

    accuracy                           0.92      8400
   macro avg       0.92      0.92      0.92      8400
weighted avg       0.92      0.92      0.92      8400