In [75]:
import pandas as pd
import requests

# Making Weather Dataset

In [76]:
api_key = "781dd18326b26dc940f9fc29a3c43d94"

cities = ["Islamabad","Karachi","Lahore","Peshawar","Quetta","Faisalabad","Multan","Hyderabad","Sialkot","Gujranwala"]
rows = []

for city in cities:
    response = requests.get(f"https://api.openweathermap.org/data/2.5/weather?q={city}&appid={api_key}")
    data = response.json()
    rows.append({
        "City": city,
        "Temperature": data["main"]["temp"],
        "Humidity": data["main"]["humidity"],
        "Pressure": data["main"]["pressure"],
        "Wind Speed": data["wind"]["speed"],
        "Weather": data["weather"][0]["main"]
    })

df = pd.DataFrame(rows)

In [77]:
pd.DataFrame(df)

         City  Temperature  Humidity  Pressure  Wind Speed Weather
0   Islamabad       305.84        67      1004        0.79    Rain
1     Karachi       303.50        66      1003        6.79  Clouds
2      Lahore       313.53        32      1000        0.64  Clouds
3    Peshawar       308.75        43      1000        2.63   Clear
4      Quetta       306.11        11      1005        3.36  Clouds
5  Faisalabad       314.44        29       999        2.19  Clouds
6      Multan       314.46        30       999        3.76  Clouds
7   Hyderabad       303.20        59      1007        6.49    Rain
8     Sialkot       311.30        39      1000        2.51  Clouds
9  Gujranwala       313.43        34       999        0.15  Clouds

In [78]:
df.to_csv('Pakistan_Weather.csv')

# Making Country Dataset

In [79]:
response = requests.get(
  'https://api.restcountries.com/countries/v5?q=canada',
  headers={'Authorization': 'Bearer rc_live_43b41c1676034c90ad414a59faf25736'})
print(response.status_code)
print(response.json())

200
{'data': {'objects': [{'names': {'alternates': [], 'common': 'Canada', 'native': {'eng': {'common': 'Canada', 'official': 'Canada'}, 'fra': {'common': 'Canada', 'official': 'Canada'}}, 'official': 'Canada', 'translations': {'ara': {'common': 'كندا', 'official': 'كندا'}, 'bre': {'common': 'Kanada', 'official': 'Kanada'}, 'ces': {'common': 'Kanada', 'official': 'Kanada'}, 'cym': {'common': 'Canada', 'official': 'Canada'}, 'deu': {'common': 'Kanada', 'official': 'Kanada'}, 'est': {'common': 'Kanada', 'official': 'Kanada'}, 'fas': {'common': 'کانادا', 'official': 'کانادا'}, 'fin': {'common': 'Kanada', 'official': 'Kanada'}, 'fra': {'common': 'Canada', 'official': 'Canada'}, 'hrv': {'common': 'Kanada', 'official': 'Kanada'}, 'hun': {'common': 'Kanada', 'official': 'Kanada'}, 'ind': {'common': 'Kanada', 'official': 'Kanada'}, 'ita': {'common': 'Canada', 'official': 'Canada'}, 'jpn': {'common': 'カナダ', 'official': 'カナダ'}, 'kor': {'common': '캐나다', 'official': '캐나다'}, 'nld': {'common': 'Canada', 'official': 'Canada'}, 'pol': {'common': 'Kanada', 'official': 'Kanada'}, 'por': {'common': 'Canadá', 'official': 'Canadá'}, 'rus': {'common': 'Канада', 'official': 'Канада'}, 'slk': {'common': 'Kanada', 'official': 'Kanada'}, 'spa': {'common': 'Canadá', 'official': 'Canadá'}, 'srp': {'common': 'Канада', 'official': 'Канада'}, 'swe': {'common': 'Kanada', 'official': 'Kanada'}, 'tur': {'common': 'Kanada', 'official': 'Kanada'}, 'urd': {'common': 'کینیڈا', 'official': 'کینیڈا'}, 'zho': {'common': '加拿大', 'official': '加拿大'}}}, 'codes': {'alpha_2': 'CA', 'alpha_3': 'CAN', 'ccn3': '124', 'cioc': 'CAN', 'fifa': 'CAN', 'fips': 'CA', 'gec': 'CA'}, 'capitals': [{'attributes': {'administrative': False, 'constitutional': False, 'executive': False, 'judicial': False, 'legislative': False, 'primary': True}, 'coordinates': {'lat': 45.42, 'lng': -75.7}, 'name': 'Ottawa'}], 'flag': {'colors': {'dominant': '#fcfaf5', 'palette': [{'hex': '#fcfaf5', 'proportion': 0.35886481537992065}, {'hex': '#ff181b', 'proportion': 0.6341165700335673}, {'hex': '#ff8d94', 'proportion': 0.00183094293561184}, {'hex': '#ff9ea3', 'proportion': 0.0012206286237412267}, {'hex': '#ffbbbd', 'proportion': 0.00183094293561184}, {'hex': '#ff7a6b', 'proportion': 0.00091547146780592}, {'hex': '#ff5c4f', 'proportion': 0.0012206286237412267}, {'hex': '#f27400', 'proportion': 0}], 'prominent': '#ff181b', 'swatches': {'dark_muted': None, 'dark_vibrant': None, 'light_muted': '#ffbbbd', 'light_vibrant': '#ff7a6b', 'muted': '#ff9ea3', 'vibrant': '#ff181b'}}, 'description': 'The flag of Canada is composed of a red vertical band on the hoist and fly sides and a central white square that is twice the width of the vertical bands. A large eleven-pointed red maple leaf is centered in the white square.', 'emoji': '🇨🇦', 'html_entity': '&#127464;&#127462;', 'unicode': 'U+1F1E8 U+1F1E6', 'url_png': 'https://flags.restcountries.com/v5/w640/ca.png', 'url_svg': 'https://flags.restcountries.com/v5/svg/ca.svg'}, 'region': 'Americas', 'subregion': 'North America', 'area': {'kilometers': 9984670, 'miles': 3855101.1}, 'assets': [], 'borders': ['USA'], 'calling_codes': ['1'], 'cars': {'driving_side': 'right', 'signs': ['CDN']}, 'classification': {'dependency': False, 'dependency_type': '', 'disputed': False, 'iso_status': 'official', 'sovereign': True, 'un_member': True, 'un_observer': False}, 'continents': ['North America'], 'coordinates': {'lat': 60, 'lng': -95}, 'currencies': [{'code': 'CAD', 'name': 'Canadian dollar', 'symbol': '$'}], 'date': {'academic_year_start': {'day': 1, 'month': 9}, 'fiscal_year_start': {'corporate': {'basis': 'convention', 'day': 1, 'month': 1}, 'government': {'day': 1, 'month': 4}, 'personal': {'day': 1, 'month': 1}}, 'start_of_week': 'sunday'}, 'demonyms': {'eng': {'f': 'Canadian', 'm': 'Canadian'}, 'fra': {'f': 'Canadienne', 'm': 'Canadien'}}, 'economy': {'gini_coefficient': {'2018': 32.5, '2019': 31.8, '2020': 29.9, '2021': 31.1, '2022': 31.5}}, 'government_type': 'Federal parliamentary constitutional monarchy', 'landlocked': False, 'languages': [{'bcp47': 'en', 'iso639_1': 'en', 'iso639_2b': 'eng', 'iso639_2t': 'eng', 'iso639_3': 'eng', 'name': 'English', 'native_name': 'English'}, {'bcp47': 'fr', 'iso639_1': 'fr', 'iso639_2b': 'fre', 'iso639_2t': 'fra', 'iso639_3': 'fra', 'name': 'French', 'native_name': 'français'}], 'leaders': [{'message': 'data.leaders is only available on paid plans. Go to https://restcountries.com/plans to make updates to your account.', 'sample': 'https://files-03.restcountries.com/countries.00/sample.leaders.json'}], 'links': {'google_maps': 'https://goo.gl/maps/jmEVLugreeqiZXxbA', 'official': 'https://www.canada.ca', 'open_street_maps': 'https://www.openstreetmap.org/relation/1428125', 'wikipedia': 'https://en.wikipedia.org/wiki/Canada'}, 'memberships': {'african_union': False, 'arab_league': False, 'asean': False, 'brics': False, 'commonwealth': True, 'eu': False, 'eurozone': False, 'g20': True, 'g7': True, 'nato': True, 'oecd': True, 'opec': False, 'schengen': False, 'un': True}, 'number_format': {'decimal_separator': '.', 'thousands_separator': ','}, 'parent': {'alpha_2': '', 'alpha_3': ''}, 'population': 41417056, 'postal_code': {'format': '@#@ #@#', 'regex': '^([ABCEGHJKLMNPRSTVXY]\\d[ABCEGHJKLMNPRSTVWXYZ]) ?(\\d[ABCEGHJKLMNPRSTVWXYZ]\\d)$'}, 'timezones': ['UTC-08:00', 'UTC-07:00', 'UTC-06:00', 'UTC-05:00', 'UTC-04:00', 'UTC-03:30'], 'tlds': ['.ca'], 'units': {'measurement_system': 'metric', 'temperature_scale': 'Celsius'}, 'uuid': '189581ed-44b0-47d7-9849-6b097401a7d6', '_match': [{'path': 'flag.description', 'value': 'The flag of Canada is composed of a red vertical band on the hoist and fly sides and a central white square that is twice the width of the vertical bands. A large eleven-pointed red maple leaf is centered in the white square.'}, {'path': 'names.native.eng.common', 'value': 'Canada'}, {'path': 'names.native.eng.official', 'value': 'Canada'}, {'path': 'names.native.fra.common', 'value': 'Canada'}, {'path': 'names.native.fra.official', 'value': 'Canada'}, {'path': 'names.common', 'value': 'Canada'}, {'path': 'names.official', 'value': 'Canada'}, {'path': 'names.translations.cym.common', 'value': 'Canada'}, {'path': 'names.translations.cym.official', 'value': 'Canada'}, {'path': 'names.translations.fra.common', 'value': 'Canada'}, {'path': 'names.translations.fra.official', 'value': 'Canada'}, {'path': 'names.translations.ita.common', 'value': 'Canada'}, {'path': 'names.translations.ita.official', 'value': 'Canada'}, {'path': 'names.translations.nld.common', 'value': 'Canada'}, {'path': 'names.translations.nld.official', 'value': 'Canada'}], '_meta': {'lastUpdatedTimestamp': 1784526832}}], 'meta': {'total': 1, 'count': 1, 'limit': 25, 'offset': 0, 'more': False, 'request_id': '6f0cac54-b7d5-4123-bcea-c8c036ffb405', 'duration': 44}}}

In [80]:
data = response.json()["data"]["objects"]
df = pd.json_normalize(data)
df.head()

,capitals,region,subregion,assets,borders,calling_codes,continents,currencies,government_type,landlocked,...,memberships.un,number_format.decimal_separator,number_format.thousands_separator,parent.alpha_2,parent.alpha_3,postal_code.format,postal_code.regex,units.measurement_system,units.temperature_scale,_meta.lastUpdatedTimestamp
0,"[{'attributes': {'administrative': False, 'con...",Americas,North America,[],[USA],[1],[North America],"[{'code': 'CAD', 'name': 'Canadian dollar', 's...",Federal parliamentary constitutional monarchy,False,...,True,.,",",,,@#@ #@#,^([ABCEGHJKLMNPRSTVXY]\d[ABCEGHJKLMNPRSTVWXYZ]...,metric,Celsius,1784526832

In [81]:
df[['continents','region','subregion','borders','currencies','government_type','capitals','landlocked']]

,continents,region,subregion,borders,currencies,government_type,capitals,landlocked
0,[North America],Americas,North America,[USA],"[{'code': 'CAD', 'name': 'Canadian dollar', 's...",Federal parliamentary constitutional monarchy,"[{'attributes': {'administrative': False, 'con...",False

There are many list of dictionaries so we have to simplify it first

In [82]:
clean_df = pd.DataFrame({
    "Country": df["names.common"],
    "Region": df["region"],
    "Subregion": df["subregion"],
    "Capital": df["capitals"].str[0].str["name"],
    "Currency": df["currencies"].str[0].str["name"],
    "Currency Code": df["currencies"].str[0].str["code"],
    "Population": df["population"],
    "Continent": df["continents"].str[0],
    "Landlocked": df["landlocked"]
})

clean_df

,Country,Region,Subregion,Capital,Currency,Currency Code,Population,Continent,Landlocked
0,Canada,Americas,North America,Ottawa,Canadian dollar,CAD,41417056,North America,False

In [83]:
clean_df.to_csv('Countries_Details.csv')