In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('D:/Important Files/Machine Learning/Datasets/train.csv').drop(columns=['Sex','Age','Ticket','Cabin','Embarked'])
df.head(5)

,PassengerId,Survived,Pclass,Name,SibSp,Parch,Fare
0,1,0,3,"Braund, Mr. Owen Harris",1,0,7.2500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,0,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",0,0,7.9250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,0,53.1000
4,5,0,3,"Allen, Mr. William Henry",0,0,8.0500

In [3]:
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
df[['SibSp', 'Parch', 'FamilySize']].head()

   SibSp  Parch  FamilySize
0      1      0           2
1      1      0           2
2      0      0           1
3      1      0           2
4      0      0           1

## 4. Aggregation-Based (Grouped) Features:

### a. Average Fare per Passenger Class:

In [4]:
class_fare_avg = df.groupby('Pclass')['Fare'].transform('mean')
df['AvgFareByClass'] = class_fare_avg
df[['Pclass', 'Fare', 'AvgFareByClass']].head()

   Pclass     Fare  AvgFareByClass
0       3   7.2500       13.675550
1       1  71.2833       84.154687
2       3   7.9250       13.675550
3       1  53.1000       84.154687
4       3   8.0500       13.675550

### b. Family Group Size by Surname:

In [5]:
df['Title'] = df['Name'].str.extract(r',\s*([^\.]*)\.')
df['Title'].value_counts()

Title
Mr              517
Miss            182
Mrs             125
Master           40
Dr                7
Rev               6
Col               2
Mlle              2
Major             2
Ms                1
Mme               1
Don               1
Lady              1
Sir               1
Capt              1
the Countess      1
Jonkheer          1
Name: count, dtype: int64

In [6]:
df['Surname'] = df['Name'].str.extract(r'^([^,]*),')
df[['Name', 'Surname', 'Title']].head()

                                                Name    Surname Title
0                            Braund, Mr. Owen Harris     Braund    Mr
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    Cumings   Mrs
2                             Heikkinen, Miss. Laina  Heikkinen  Miss
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)   Futrelle   Mrs
4                           Allen, Mr. William Henry      Allen    Mr

In [7]:
surname_counts = df.groupby('Surname')['PassengerId'].transform('count')
df['SurnameGroupSize'] = surname_counts
df[['Surname', 'FamilySize', 'SurnameGroupSize']].head(10)

     Surname  FamilySize  SurnameGroupSize
0     Braund           2                 2
1    Cumings           2                 1
2  Heikkinen           1                 1
3   Futrelle           2                 2
4      Allen           1                 2
5      Moran           1                 3
6   McCarthy           1                 1
7    Palsson           5                 4
8    Johnson           3                 6
9     Nasser           2                 2

### c. Survival Rate by Title:

In [8]:
title_survival_rate = df.groupby('Title')['Survived'].transform('mean')
df['TitleSurvivalRate'] = title_survival_rate
df[['Title', 'Survived', 'TitleSurvivalRate']].head(10)

    Title  Survived  TitleSurvivalRate
0      Mr         0           0.156673
1     Mrs         1           0.792000
2    Miss         1           0.697802
3     Mrs         1           0.792000
4      Mr         0           0.156673
5      Mr         0           0.156673
6      Mr         0           0.156673
7  Master         0           0.575000
8     Mrs         1           0.792000
9     Mrs         1           0.792000

In [9]:
df.head(5)

,PassengerId,Survived,Pclass,Name,SibSp,Parch,Fare,FamilySize,AvgFareByClass,Title,Surname,SurnameGroupSize,TitleSurvivalRate
0,1,0,3,"Braund, Mr. Owen Harris",1,0,7.2500,2,13.675550,Mr,Braund,2,0.156673
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,0,71.2833,2,84.154687,Mrs,Cumings,1,0.792000
2,3,1,3,"Heikkinen, Miss. Laina",0,0,7.9250,1,13.675550,Miss,Heikkinen,1,0.697802
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,0,53.1000,2,84.154687,Mrs,Futrelle,2,0.792000
4,5,0,3,"Allen, Mr. William Henry",0,0,8.0500,1,13.675550,Mr,Allen,2,0.156673